[package]
name = "bootstrap"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
api.workspace = true
tokio.workspace = true
sea-orm.workspace = true
uuid.workspace = true
chrono.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
dotenvy.workspace = true
